/**
 * Centralized UI copy. Plain, short, active voice.
 * Keep domain terms: GRN, Lark, Ping, Reconciliation.
 */
export const copy = {
  // Navbar
  navDescOverview: 'Key numbers & summary',
  navDescFees: 'Fees & reconciliation gap',
  navDescCoverage: 'Outlet coverage',
  navDescSalesByOutlet: 'Net sales ranked, all 44 outlets',
  navDescPurchasesByOutlet: 'GRN received, all 44 outlets',
  // Unused: the grossSalesByOutlet page was removed; section 6 is now purchasesToNetSales.
  navDescGrossSalesByOutlet: 'Menu price before discount, per outlet',
  navDescPLByOutlet: 'Net sales − purchases, per outlet',
  navReconciled: 'Reconciled',
  navOutletScope: '44 outlets · 2 pre-opening',
  navDashboardTab: 'Dashboard',
  navTasksTab: 'Tasks',
  navMatrixTab: 'Full Matrix View',

  // SalesDashboard header
  dashEyebrow: 'US Pizza · Corporate',
  dashTitle: 'May 2026 P&L',
  dashExportReady: 'Export ready.',
  dashReporting: 'Reporting: May 2026',
  dashExportCsv: 'Export CSV',

  // OverviewPage
  overviewSubtitle: 'May 2026 · 44 outlets',
  overviewSubtitlePrefix: 'May 2026',
  overviewAutoSummary: 'Auto summary',
  overviewAutoGenerated: 'Auto-generated',
  overviewGapNote: 'Section 2 has a RM 158,143 gap that is not explained yet.',
  overviewReconState: 'Books Closed (May 31)',
  overviewReconLabel: 'Reconciliation State',
  overviewNetSalesNote: 'After discounts',
  overviewPurchasesCaveat: 'Does not include labour, utilities, or rent.',
  overviewGrossProfitCaveat: 'Not final — only purchases counted so far. Other costs still being checked.',
  overviewViewCalc: 'Show calculation',
  overviewHideCalc: 'Hide calculation',

  // CommissionFeesPage
  feesGapIntro:
    'The fee report and the bank statements use different dates.',
  feesGapOutro: 'We need the original invoices to fix this.',
  feesUnexplained: 'Not explained:',
  feesDifferenceLabel: 'Difference',
  feesDeductedLabel: 'Taken out of settlements',
  feesReportTotalLabel: '1. Total Fees Reported',
  feesFootnote:
    'From May delivery-partner statements. Negative numbers are refunds paid back.',
  feesTableTitle: 'Platform Fees, Listed (May 2026)',
  feesTableSubtitle:
    'Includes Grab, FoodPanda, ShopeeFood, and US Pizza Apps. Does not include in-store POS.',

  // DataCoveragePage
  coverageAssessed: 'Across 44 outlets.',
  coverageWebAppsNote: 'Both use the same US Pizza App ID.',
  coverageGrnNote: 'Used for purchases. Matched to warehouse delivery tickets.',
  coverageSearchPlaceholder: 'Search outlet by name, store code, or region...',
  coverageNoMatch: 'No outlets match your search and filters.',

  // App footer
  footerOps: 'Corporate Operations',
  footerLive: 'Live · 44 outlets · MY US Pizza & Sabah',
} as const;
