/**
 * Centralized UI copy. Plain, short, active voice.
 * Keep domain terms: GRN, Lark, Ping, Reconciliation.
 */
export const copy = {
  // Navbar
  navDescOverview: 'Key figures & summary',
  navDescFees: 'Fees & reconciliation gap',
  navDescCoverage: 'Outlet coverage',
  navReconciled: 'Reconciled',
  navOutletScope: '44 outlets · 2 pre-opening',
  navDashboardTab: 'Dashboard',
  navTasksTab: 'Tasks',
  navMatrixTab: 'Full Matrix View',

  // SalesDashboard header
  dashEyebrow: 'US Pizza · Corporate',
  dashTitle: 'May 2026 P&L',
  dashExportReady: 'Export ready.',
  dashReporting: 'Reporting: May 2026',
  dashExportCsv: 'Export CSV',

  // OverviewSection
  overviewSubtitle: 'May 2026 · 44 outlets',
  overviewSubtitlePrefix: 'May 2026',
  overviewAutoSummary: 'Auto summary',
  overviewAutoGenerated: 'Auto-generated',
  overviewGapNote: 'Section 2 has an open RM 158,143 difference.',
  overviewReconState: 'Books Closed (May 31)',
  overviewReconLabel: 'Reconciliation State',
  overviewNetSalesNote: 'After discounts',
  overviewPurchasesCaveat: 'Excludes labour, utilities, and rent.',
  overviewGrossProfitCaveat: 'Provisional — purchases only. Other costs pending audit.',
  overviewViewCalc: 'View calculation',
  overviewHideCalc: 'Hide calculation',

  // CommissionFeesSection
  feesGapIntro:
    'The fee report and bank statements use different schedules.',
  feesGapOutro: 'Source invoices needed to close this.',
  feesUnexplained: 'Unexplained:',
  feesDifferenceLabel: 'Difference',
  feesDeductedLabel: 'Deducted in settlements',
  feesReportTotalLabel: '1. Fee Report Item Total',
  feesFootnote:
    'From May delivery-partner statements. Adjustments in green are refunds credited back.',
  feesTableTitle: 'Platform Fee Itemization (May 2026)',
  feesTableSubtitle:
    'Includes Grab, FoodPanda, ShopeeFood, and US Pizza Apps. In-store POS excluded.',

  // DataCoverageSection
  coverageAssessed: 'Across 44 units.',
  coverageWebAppsNote: 'Both map to the same US Pizza App ID.',
  coverageGrnNote: 'Basis for purchases. Matched to warehouse delivery tickets.',
  coverageSearchPlaceholder: 'Search outlet by name, store code, or region...',
  coverageNoMatch: 'No outlets match the selected search and filter criteria.',

  // PlatformPanel
  panelSubtitle: 'Cash received after discounts and fees.',
  panelSource: 'From platform settlement reports',

  // App footer
  footerOps: 'Corporate Operations',
  footerLive: 'Live · 44 outlets · MY US Pizza & Sabah',
} as const;
